### ISSUE TITLE
Base64埋め込み画像のsrcが取得できない

### ISSUE THREAD

**Issue by yuta0381** [ktty1220/cheerio-httpcli#20]
画像をダウンロードするサンプルをGoogleの画像検索の結果の画像を
ダウンロードさせるようにしたら以下のようなエラーがでました。

試しにdownload.js:312の$elem.attr('src')の値を見てみるとundefinedでした。
```js
var fs = require('fs');
var client = require('cheerio-httpcli');

client.download.on('ready', function (stream) {
    stream.pipe(fs.createWriteStream('/path/to/image.png'));
    console.log(stream.url.href + 'をダウンロードしました');
}).on('error', function (err) {
    console.error(err.url + 'をダウンロードできませんでした: ' + err.message);
}).on('end', function () {
    console.log('ダウンロードが完了しました');
});

client.download.parallel = 4;

client.fetch('http://www.google.com/search', { q: 'node.js', tbm:'isch' }, function (err, $, res, body) {
    $('img').download();
    console.log('OK!');
});
```
```
node_modules\cheerio-httpcli\lib\cheerio\download.js:312
      var b64chk = $elem.attr('src').match(/^data:(image\/\w+);base64,([\s\S]+)$/i);
                                    ^

TypeError: Cannot read property 'match' of undefined
    at Object.<anonymous> (node_modules\cheerio-httpcli\lib\cheerio\download.js:312:37)
    at initialize.exports.each (node_modules\cheerio\lib\api\traversing.js:300:24)
    at initialize.cheerio.download (node_modules\cheerio-httpcli\lib\cheerio\download.js:300:10)
    at Object.callback (img\app.js:16:14)
    at Object.<anonymous> (node_modules\cheerio-httpcli\lib\client.js:261:17)
    at Object.<anonymous> (node_modules\cheerio-httpcli\lib\client.js:221:9)
    at Request.self.callback (node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (node_modules\request\request.js:1171:10)
```

**Comment by ktty1220** [comment]
調べてみましたが、Google画像検索結果のHTMLソース上では画像タグが以下の様になっていました。

```html
<img class="rg_ic rg_i" data-sz="f" name="ZcvDYlgt8bMONM:" alt="「node.js」の画像検索結果" jsaction="load:str.tbn" onload="google.aft&&google.aft(this)">
```

HTMLソースの時点では`img`タグに`src`属性が指定されていません。

おそらく`onload`のタイミングで`src`にbase64化された画像が差し込まれるのではないかと思います。
cheerio-httpcliでは`onload`といった動的なコンテンツ変更には対応していないので、`src`が指定されていない`img`タグの`src`を見に行ってエラーになっているといった状態です。

次バージョンで修正する予定ですが、現在masterブランチで大きめの対応を行っており、それと合わせてリリースする関係上、すぐにバージョンアップというわけにはいかない状態なので、急ぎの場合は、エラーの出た箇所を以下のように書き換えるととりあえず動くようにはなります。

```js
var b64chk = ($elem.attr('src') || '').match(/^data:(image\/\w+);base64,([\s\S]+)$/i);
```

ただ、Googleの画像検索結果が上記のように動的に`img`の`src`をセットしていることから考えると、この修正を適用しても検索結果の画像を正常に全部取得できるかどうかは分かりません。

静的コンテンツの解析がcheerio-httpcliの機能なので、その点についてはご了承ください。

**Comment by ktty1220** [comment]
こちらは0.7.0で修正されました。
